[build]
  command = "npm run build"  # Your specific build command
  publish = "build"          # Ensure this matches your output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
